version: '2'


services:
  gateway:
    image: dpsocialauth/frontend:latest
#    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
        - ../nginx/oauth2.conf:/etc/nginx/conf.d/oauth2.conf
        - ../nginx/oauth2-dev.conf:/etc/nginx/conf.d/oauth2-dev.conf
        - ../nginx/nginx.conf:/etc/nginx/nginx.conf
        - ../nginx/upstream.php:/var/www/public/upstream.php
        - ../nginx/nginx-supervisor.ini:/etc/supervisor.d/nginx-supervisor.ini
        - ../nginx/www.conf:/etc/php7/php-fpm.d/www.conf
    hostname: gateway
    container_name: ${COMPOSE_PROJECT_NAME}-gateway
    environment:
      - DOCKER_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - SERVICE_SECRET=asecret
      - DP_SITE_HOSTNAME_SUFFIX=.co.uk
    ports:
     - "8080:8080"
     - "8081:8081"
     - "8082:8082"
    links:
      - oauth2google
      - oauth2github
    network_mode: bridge

  oauth2google:
    image: dpsocialauth/proxy:latest
    command: 'oauth2_proxy --http-address="0.0.0.0:4180" --proxy-prefix=/google/oauth2 --provider=google --upstream=http://172.17.0.1:8082 --approval-prompt=force --redirect-url=http://auth.deskpro-dev.co.uk:8080/google/oauth2/callback --client-id=683505557470-el8724i1mdkr2nlfab2tfnu9gllv6dbk.apps.googleusercontent.com --client-secret=GhZbdXixgC2yEAxER-ab-RJd --email-domain=* --cookie-secret=secretssecretsecret --cookie-secure=false '
    container_name: ${COMPOSE_PROJECT_NAME}-oauth2google
    hostname: oauth2google
    network_mode: bridge

  oauth2github:
    image: dpoauth2proxy/dev:latest
    command: 'oauth2_proxy --http-address="0.0.0.0:4180" --proxy-prefix=/github/oauth2 --provider=github --upstream=http://172.17.0.1:8082 --approval-prompt=force --redirect-url=http://auth.deskpro-dev.co.uk:8080/github/oauth2/callback --client-id=fd49d9224f45f4f66e45 --client-secret=c61805fb26479a746cbae8c67744ac877a889263 --email-domain=* --email-domain=* --cookie-secret=secretssecretsecret --cookie-secure=false'
    container_name: ${COMPOSE_PROJECT_NAME}-oauth2github
    hostname: oauth2github
    network_mode: bridge

