version: '2'


services:
  gateway:
    image: dpsocialauth/frontend:latest
    hostname: gateway
    container_name: ${COMPOSE_PROJECT_NAME}-gateway
    environment:
      - DOCKER_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
      - DP_SITE_HOSTNAME_SUFFIX=.deskpro.com
    env_file:
      - gateway-env-file

  oauth2google:
    image: dpsocialauth/proxy:latest
    command: --config=/etc/oauth2_proxy.cfg --proxy-prefix=/google/oauth2 --provider=google --redirect-url="https://auth.deskpro.com/google/oauth2/callback"
    container_name: ${COMPOSE_PROJECT_NAME}-oauth2google
    hostname: oauth2google
    env_file:
      - proxy-env-file
      - google-env-file

  oauth2linkedin:
    image: dpsocialauth/proxy:latest
    command: --config=/etc/oauth2_proxy.cfg --proxy-prefix=/linkedin/oauth2 --provider=linkedin --redirect-url=https://auth.deskpro.com/linkedin/oauth2/callback
    container_name: ${COMPOSE_PROJECT_NAME}-oauth2linkedin
    hostname: oauth2linkedin
    env_file:
      - proxy-env-file
      - linkedin-env-file

  oauth2azure:
    image: dpsocialauth/proxy:latest
    command: --config=/etc/oauth2_proxy.cfg --proxy-prefix=/azure/oauth2 --provider=azure --redirect-url=https://auth.deskpro.com/azure/oauth2/callback
    env_file:
      - proxy-env-file
      - azure-env-file
